//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Access
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Microsoft.AspNet.Identity;
    using Microsoft.AspNet.Identity.EntityFramework;
    
    public partial class TimeTrackingEntities : IdentityDbContext<ApplicationUser>
    {
        public TimeTrackingEntities()
            : base("TimeTrackingEntities", throwIfV1Schema: false)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
    	base.OnModelCreating(modelBuilder);
            //throw new UnintentionalCodeFirstException();
    		//modelBuilder.Entity<IdentityUserRole>().HasKey(x => new { x.RoleId, x.UserId }).ToTable("AspNetUserRoles");
            //modelBuilder.Entity<IdentityUserLogin>().HasKey(x => x.UserId).ToTable("AspNetUserLogins");
    		//modelBuilder.Entity<AspNetUserLogin>().HasKey(x => x.UserId).ToTable("AspNetUserLogins");
                
        }
    
    	 public static TimeTrackingEntities Create()
           {
                return new TimeTrackingEntities();
            }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<MyUser> MyUsers { get; set; }
    }
}
