//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public string FirstName { get; set; }
        public string Middle { get; set; }
        public string LastName { get; set; }
        public string EmployeeNumber { get; set; }
        public string ParticipateName { get; set; }
        public string ParticipateNumber { get; set; }
        public string RepParticipatePhone { get; set; }
        public string RepParticipateEmail { get; set; }
        public string DateSelection { get; set; }
        public Nullable<int> Year { get; set; }
        public string Monday { get; set; }
        public string Sunday { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<int> ServiceCode { get; set; }
        public string PlanSection { get; set; }
        public string BackupCode { get; set; }
        public string TimeIn { get; set; }
        public string FirstMeridian { get; set; }
        public string TimeOut { get; set; }
        public string SecondMeridian { get; set; }
        public string AddlTimeIn { get; set; }
        public string ThirdMeridian { get; set; }
        public string AddlTimeOut { get; set; }
        public string FourthMeridian { get; set; }
        public Nullable<decimal> TotalHrs { get; set; }
        public string LiveIN { get; set; }
        public string Newcolumntest { get; set; }
        public string newcolumntest2 { get; set; }
        public string newcolumntest3 { get; set; }
    }
}
